### ISSUE TITLE
صفحه /AttachPage.php در لیست صفحات امکان مربوطه اضافه نشده است

### ISSUE THREAD

**Issue by milanifard** [milanifard/FAQManager#3]
کوئری ایجاد صفحات منو باید تکمیل شود.
بهتر است ابتدای فایلهای کوئری use sadaf هم گذاشته شود که کاربر اشتباها کوئری را روی دیتابیس دیگری اجرا نکند

**Comment by MKermanipoor** [comment]
fixed at 47ae733b1b8da032dd83ac12d5e0c01e47a43940
