### ISSUE TITLE
اشکال در متد getRelatedFAQ 

### ISSUE THREAD

**Issue by milanifard** [milanifard/FAQManager#5]
در کوئری این متد فرض بر این است که پرسش و پاسخهایی که حتما کد صفحه و گروه کاربری یکسان دارند مرتبط هستند در حالیکه همیشه اینگونه نیست. این دو معیار باید فقط در رتبه بندی پرسش و پاسخهای نمایش داده شده تاثیر گذار باشند

**Comment by MKermanipoor** [comment]
Fixed at cb71049f0859033e3757f4c3079ffed887314e2d
